name: Build, Optimize with Classpresso, and Deploy

on:
  workflow_run:
    workflows: [Build Tailwind CSS]
    types:
      - completed

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - run: npm install

      # Build your static site
      - name: Copy pages to public "dist" folder
        uses: canastro/copy-file-action@master
        with:
          source: pages/.
          target: dist/
          flags: '-r'

      - name: Ensure writable dist
        run: sudo chown -R $USER:$USER dist

      # Optimize classes in built HTML and CSS
      - name: Optimize HTML with Classpresso
        run: npx classpresso optimize --dir dist

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'GitHub-Actions Deploy [bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
