name: Build Tailwind CSS

on:
  push:
    branches:
      - main

jobs:
  Build_CSS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      
      - name: Install dependencies
        run: npm install
      
      - name: Build Tailwind CSS
        run: npx tailwindcss -i ./src/input.css -o ./dist/output.css
         
      - name: Commit and push
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add -A
          git commit -m "Build CSS" || echo "No changes to commit"
          git push || echo "Nothing to push"
